version: "3.8"

services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: crawler-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root1212!@#
      MYSQL_DATABASE: crawler
      MYSQL_USER: crawler
      MYSQL_PASSWORD: crawler1212!@#
    ports:
      - "13306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    restart: unless-stopped
